---
title: "Database provided for `metid`"
author:
- name: Xiaotao Shen PhD (https://www.shenxt.info/)
date: "Created on 2020-03-28 and updated on `r Sys.Date()`"
output:
  html_document:
    df_print: paged
    toc: no
  pdf_document:
    toc: no
vignette: >
  %\VignetteIndexEntry{public_data}
  %\VignettePackage{metid}
  % \VignetteEngine{knitr::rmarkdown}
  % \usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = "100%"
)
```

***

## **In-house MS2 databases from [Michael Snyder lab](http://med.stanford.edu/snyderlab.html)**

### 1. Michael Snyder HILIC databases

* <i class="fa fa-info"></i> Professor Michael Snyder's lab. More than 1,000 metabolites.

* <i class="fa fa-download"></i> [Download here]()

> If you need this database, please contact shenxt@stanford.edu

### 2. Michael Snyder RPLC databases

* <i class="fa fa-info"></i> Professor Michael Snyder's lab. More than 1,000 metabolites.

* <i class="fa fa-download"></i> [Download here]()

> If you need this database, please contact shenxt@stanford.edu

***

## **Public MS2 databases**

### 1. [HMDB database](https://hmdb.ca/downloads)

* <i class="fa fa-info"></i> HMDB database.

* <i class="fa fa-download"></i> [Download here](https://www.shenxt.info/ms2_data/hmdbDatabase0.0.2)

### 2. [MassBank database](https://massbank.eu/MassBank/)

* <i class="fa fa-info"></i> MassBank database.

* <i class="fa fa-download"></i> [Download here](https://www.shenxt.info/ms2_data/massbankDatabase0.0.2)

### 3. [MoNA database](https://mona.fiehnlab.ucdavis.edu/)

* <i class="fa fa-info"></i> MoNA database.

* <i class="fa fa-download"></i> [Download here](https://www.shenxt.info/ms2_data/monaDatabase0.0.2)

### 4. [Orbitrap database](https://mona.fiehnlab.ucdavis.edu/)

* <i class="fa fa-info"></i> Orbitrap database from MoNA.

* <i class="fa fa-download"></i> [Download here](https://www.shenxt.info/ms2_data/orbitrapDatabase0.0.1)

### 5. [Fiehn HILIC database](https://fiehnlab.ucdavis.edu/staff/kind/publications)

* <i class="fa fa-info"></i> HILIC MS2 database from Fiehn lab.

* <i class="fa fa-download"></i> [Download here](https://www.shenxt.info/ms2_data/fiehn_hilic_database0.0.1)

<!-- ### 6. Exposome database -->

<!-- * <i class="fa fa-info"></i> Some chemical exposome database -->

<!-- * <i class="fa fa-download"></i> [Download here](https://www.shenxt.info/ms2_data/exposureDatabase) -->

> If you need this database, please contact shenxt@stanford.edu.

***

## **Public $MS^1$ databases**

### 1. [HMDB MS1 database](https://hmdb.ca/downloads)

* <i class="fa fa-info"></i> HMDB MS1 database.

* <i class="fa fa-download"></i> [Download here](https://www.shenxt.info/ms2_data/hmdbMS1Database0.0.1)


### 2. [KEGG MS1 database](https://www.genome.jp/kegg/compound/)

* <i class="fa fa-info"></i> KEGG MS1 database.

* <i class="fa fa-download"></i> [Download here](https://www.shenxt.info/ms2_data/keggMS1Database_1.0)

### 3. [Drugbank database](https://go.drugbank.com/releases/latest)

* <i class="fa fa-info"></i> Drugbank MS1 database.

* <i class="fa fa-download"></i> [Download here](https://www.shenxt.info/ms2_data/drugbankMS1Database5.1.8)

<!-- ### 4. [Foodb database](https://foodb.ca/downloads) -->

<!-- * <i class="fa fa-info"></i> Foodb MS1 database. -->

<!-- * <i class="fa fa-download"></i> [Download here](https://www.shenxt.info/ms2_data/hmdbMS1Database0.0.1) -->

### 4. [T3DB database](http://www.t3db.ca/downloads)

* <i class="fa fa-info"></i> T3DB MS1 database.

* <i class="fa fa-download"></i> [Download here](https://www.shenxt.info/ms2_data/t3dbMS1Database_1.0)

### 5. [Blood exposome database](https://bloodexposome.org/#/download)

* <i class="fa fa-info"></i> Blood exposome MS1 database.

* <i class="fa fa-download"></i> [Download here](https://www.shenxt.info/ms2_data/bloodExposomeMS1Database_1.0)











